### ISSUE TITLE
/root/motioneyeos/output/.../target/var/log: File exists

### ISSUE THREAD

**Issue by cedricve** [ccrisan/thingos#41]
A couple of packages such as PHP, Nginx, are trying to create following directory /root/motioneyeos/output/raspberrypi3/target/var/log.

However this has been declared as a symbol link to /data/log. Due this the installation step stops the build. Any ideas or best practices how to overcome (without updating the packages)?

<img width="933" alt="Screenshot 2019-11-29 at 13 31 38" src="https://user-images.githubusercontent.com/1546779/69869257-9adbea80-12ac-11ea-8a5a-80398794163b.png">

**Comment by cedricve** [comment]
sorry closed by accident.

**Comment by cedricve** [comment]
resolved

**Comment by ccrisan** [comment]
@cedricve how did you solve the problem?

**Comment by cedricve** [comment]
I encountered it when doing a rebuild (While executing the postscript.sh the symlink was created). https://github.com/ccrisan/thingos/blob/dev/board/common/postscript.sh#L36 So when I do clean build it works as expected, but not when you add the package afterwards. 

Meanwhile I encountered another (similar) issue at the end of the buildscript. 

<img width="1032" alt="Screenshot 2019-11-29 at 21 47 03" src="https://user-images.githubusercontent.com/1546779/69889545-cf25ca00-12f1-11ea-8761-4740f06998fc.png">

It is caused by this symbol link (also in postscript.sh) https://github.com/ccrisan/thingos/blob/dev/board/common/postscript.sh#L34. When I disable the package *nginx* for example then it works expected.

**Comment by cedricve** [comment]
It looks like makedevs does something special, when nginx package is turned on. Any idea @ccrisan ?

**Comment by cedricve** [comment]
Found the issue, when nginx is enabled the build will fail due to this https://github.com/ccrisan/thingos/blob/dev/package/nginx/nginx.mk#L28-L30.

When creating the rootfs.tar file, it will try to create an nginx directory which doesnt work because it's already defined as a symbol link. This might be fixed by having an init script which creates the /var/lib/nginx directory on boot. However this is how I solved it.

**Comment by ccrisan** [comment]
@cedricve thanks for digging into this and finding the root cause of the problem.

While your solution is valid and does the job, I'd recommend:

1. A small adjustment to your solution: use the [`board/common/overlay`](https://github.com/ccrisan/thingos/tree/dev/board/common/overlay) folder to create initial structure for your target system.
2. PR https://github.com/ccrisan/thingos/pull/46 which is supposed to provide a proper fix for this issue and alike. See [Overlay Filesystems](https://github.com/ccrisan/thingos/wiki/Partitions#overlay-filesystems) for more details.

**Comment by cedricve** [comment]
pleasure!
