### ISSUE TITLE
FAT32 /data partition 

### ISSUE THREAD

**Issue by arky** [ccrisan/thingos#60]
Is it possible to format /data partition as FAT32 instead of Ext4?

**Comment by ccrisan** [comment]
Probably yes, but this is not something I would recommend and it's definitely going to require some changes throughout the thingOS code.

Reasons why I don't recommend this include:
 * data partition is used for everything that is writable, including various config, log and data files for various programs; some of them may probably encounter issues due to lack of permissions on the filesystem
 * having the data partition on a non-journaled filesystem is very likely to result in data loss upon first power loss

**Comment by arky** [comment]
Thanks for a quick response @ccrisan. 

Perhaps I should present a use case for a FAT32 partition. I would like to save media (JPEG) from qcam program to a FAT32 partition. So when a user inserts the micro SDCard into a Windows machine. The FAT32 partition would be mount automatically and would be readable. 

Perhaps there is someway to achieve this using ThingOS. Thanks

**Comment by ccrisan** [comment]
I guess that could be a valid reason for having a Windows-friendly partition. However, the correct solution would be to have a separate, fourth partition dedicated to this purpose. This way, all services relying on the existing data partition would still function properly, while they could also produce content on the fourth auxiliar partition.

I currently don't have the time to work on such a feature, but here's what I believe would be the list of required changes:

 * [/etc/init.d/S00datapart](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/init.d/S00datapart) should leave space for the 4th partition, instead of allocating all remaining space
 * [/etc/init.d/S00datapart](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/init.d/S00datapart) should create the 4th data partition
 * [/etc/init.d/S00datapart](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/init.d/S00datapart) should run `fsck` on the 4th partition as well
 * [/etc/fstab.disk](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/fstab.disk) should list the 4th partition so that it can be picked up by [/etc/init.d/S01mountall](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/init.d/S01mountall)
 * [/etc/init.d/S02restorebackups](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/init.d/S02restorebackups) could also take into account the 4th partition
 * [/sbin/fwupdate](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/sbin/fwupdate)
 * various Wiki pages would need to be updated to reflect the new partition layout

**Comment by arky** [comment]
Thanks @ccrisan for the directions. I'll try to make changes, if it works well. I'll send PR with my contribution. Closing this bug as resolved for now.

**Comment by jasaw** [comment]
A bit late to the discussion, but I just want to chime in here. Last time I tried multiple FAT32 partitions on an SD card, Windows only mounted the first partition and ignored the rest. What I ended up doing (on my raspberry pi) was expand the boot partition to 15GB on my 16GB SD card, and use the boot partition as storage. @arky you may need to do the same thing.

**Comment by ccrisan** [comment]
The boot partition could be used for this purpose, but obviously with its own shortcomings.

The [board/common/mkimage.sh](https://github.com/ccrisan/thingos/blob/dev/board/common/mkimage.sh#L27) could be changed to increase the `BOOT_SIZE` parameter to something bigger, while [fstab.disk](https://github.com/ccrisan/thingos/blob/dev/board/common/overlay/etc/fstab.disk) could be changed to mount `/boot` read-write.

The shortcomings that I see include:
 * the boot partition must have a fixed size; it cannot grow to fit the remaining space
 * the firmware update mechanism will effectively remove the extra data stored on the boot partition; one would need to backup and restore it across updates or change the firmware update mechanism to copy files instead of `dd`-ing the boot partition.
 * the system will become more susceptible to power loss, especially since we're talking about the boot partition
