### ISSUE TITLE
Restart wifi instead of reboot whole system

### ISSUE THREAD

**Issue by avanc** [ccrisan/thingos#63]
This is actually not a bug report, but more a question to understand design decisions.

Why is the system rebooted if network connection (in my case wifi) is lost? Is it due to the main use case of thingOS (motioneyeos), where missing connectivity would significantly reduce the main purpose? Or is it not that easy to reconnect on a Raspberry Pi?

### Background
I'm using thingOS for a [digital photoframe](https://github.com/avanc/photos). thingOS helped a lot to get a working prototype quickly up and running. In that use-case it is not that fatal if network is done, as the images are stored locally.
Thus, I'm investigating the best way to just restart networking instead of rebooting the whole system and I want to make sure there are not already known pitfalls.

**Comment by ccrisan** [comment]
@avanc while I'm not saying that the choice of rebooting upon network loss is the best choice, here are some reasons that led to it:

 * thingOS was designed with network connectivity in mind, meaning that losing upstream connection is considered fatal issue (i.e. the system can't work properly without it)
 * connectivity losses may be caused by faulty drivers or hardware issues that could only be recovered from (if at all) by a reboot
 * services running on thingOS might not be designed well enough to be resilient to network reconnections; rebooting the OS will effectively restart them
 * the OS itself is supposed to behave like an "embedded" system, where anything that goes wrong would trigger a reset
 * the OS is supposed to boot fast enough so that the downtime caused by the reboot itself should be comparable to the downtime caused by a network reconnection

This being said, if you don't neet a network connection, you can disable it by setting [OS_NETWORKLESS=true](https://github.com/ccrisan/thingos/wiki/os.conf#os_networkless). Or you can tweak the [panic action](https://github.com/ccrisan/thingos/wiki/Panic-Reboots) handling script so that it doesn't reboot on network loss (or at all).

I have toyed with the idea of a `/etc/network/interfaces` file and the underlying mechanism and as far as I remember, it actually works for configuring the interfaces, but it won't do Wi-Fi reconnections.

I know the network connection mechanism is far from ideal and I am open to suggestions, but I can't promise to implement anything that is too disruptive or radically changes the way the system currently works.

**Comment by avanc** [comment]
Thanks for the background information. I'm considering to keep my changes small an possible: Do not stop boot process, by doing a reboot with higher delay (e.g. 1 hour) so the photoframe is showing pictures most of the time.
