### ISSUE TITLE
How to create wpa_supplicant, where to put it and what should be in it?

### ISSUE THREAD

**Issue by johncblacker** [ccrisan/thingos#74]
I'm trying to create a wpa_supplicant but am having problems.  I tried creating one and putting it in the /boot directory and that wouldn't work - said read-only file system; next I tried putting it in /etc directory - same error; lastly I tried putting it in the /data/etc directory and that worked, but it wasn't accepted.  I followed the instructions on: https://github.com/ccrisan/motioneyeos/wiki/Wifi-Preconfiguration but it's really not clear where to put the file and after I booted by reconnecting my ethernet connection, the wpa_supplicant I put in /data/etc has been reset back to the default one.  So, I need some guidance here.

**Comment by ccrisan** [comment]
The contents and file format of `wpa_supplicant.conf` can generally be found online, but for a simple example that should work with most common home Wi-Fi networks, see https://github.com/ccrisan/thingos/wiki/wpa_supplicant.conf.

If you put the file on the boot partition, that's supposed to happen from your PC/laptop, when you plug the SD card into it. If you do it on a live running OS, you'll find the partition is read-only. In fact this method was designed so that you can preconfigure the Wi-Fi settings when you only have a Windows machine and can only deal with FAT32 filesystems (not Linux extended).

If you want to configure it while running the live OS, you can place it at `/data/etc/wpa_supplicant.conf`.
