### ISSUE TITLE
Question: Where do the initrd.gz files come from?

### ISSUE THREAD

**Issue by jbliesener** [ccrisan/thingos#87]
Hi,

from what I understand, in a normal linux system, initrd.gz files are created with the initramfs-tools and are dependent on the kernel version.

Yet, I see that in thingos, every board comes with a specific initrd.gz file (directly in the boards directory) that seems to be pre-built somewhere externally. I see that the update mechanism is built around this.

Can you shed a light on how these initrd files are created and why they don't depend on the specific kernel version that is built with thingos?

Any chance that the source code will be provided as a buildroot package?

**Comment by ccrisan** [comment]
> from what I understand, in a normal linux system, initrd.gz files are created with the initramfs-tools and are dependent on the kernel version.

Indeed, on regular Linux distros, initrd/initramfs images depend on the kernel and usually come together with the kernel itself.

> Yet, I see that in thingos, every board comes with a specific initrd.gz file (directly in the boards directory) that seems to be pre-built somewhere externally. I see that the update mechanism is built around this.

Indeed, the firmware update mechanism of thingOS is built around these initrd files you've identified.

> Can you shed a light on how these initrd files are created and why they don't depend on the specific kernel version that is built with thingos?

On regular distros, an initrd/initramfs is used to boot a running Linux without mounting the real root filesystem right away, so that we can repair it if needed beforehand. On thingOS this is not needed since we're using a read-only (immutable) root partition.

The reason why initrd is highly dependent on the kernel, on regular distros, is that it comes with required modules (drivers) that are tightly coupled to the kernel build. These modules are required in the initrd phase because the initrd is actually supposed to boot a fully functional operating system. On thingOS, we don't need a fully functional OS to do the firmware update - we just need storage and filesystem drivers (which are built in the kernel, not as external modules).

> Any chance that the source code will be provided as a buildroot package?

I'm not sure I understand your question, but the answer is probably _no_, as there's nothing really about thingOS that can be provided as a BuildRoot package. However, the plan, in the long run, is to transform thingOS into an external BuildRoot layers, so that we can easily "upgrade" the underlying BuildRoot version.

> Where do the initrd.gz files come from?

They are built from the thingOS source itself, but using the `./build.sh ${BOARD} initramfs` command. They will simply contain the initramfs skeleton instead of the normal thingOS root filesystem skeleton.

I hope my answer makes things a bit clearer and thanks for asking such a pertinent question.

**Comment by jbliesener** [comment]
Got it, thank you very much.

What confused me is that initrd.gz is part of the source code repository. I now understand that it actually _is_ built within #thingos with the configs/<board>_initramfs_defconfig configuration and then copied with the board-specific cpinitramfs.sh to the board directory. 

Is it intentional that these files are part of the git repository and even form commits (like commit 41b21eb) If not, it may be an idea to include `/board/*/initrd.gz` in `.gitignore` and make sure that they're built together with the main operating system.

As for making thingOS an external BuildRoot layer: great, that would make it much easier to keep track with BuildRoot. Go for it!

**Comment by ccrisan** [comment]
The initramfs image files are intended to be part of the source tree as the build process doesn't also build them automatically. I know this is not ideal and we might change that at some point, but for now it is expected to see those binary files added to git.
